package io.github.user32694.ledgerplatform.audit;

public enum AuditAction {
    ACCOUNT_CREATE,
    PAYMENT_TOP_UP,
    PAYMENT_TRANSFER,
    PAYMENT_REFUND,
    PAYMENT_REVERSAL,
    RECONCILIATION_IMPORT,
    RECONCILIATION_RUN,
    RECONCILIATION_CASE_CLAIM,
    RECONCILIATION_CASE_RELEASE,
    RECONCILIATION_CASE_RESOLVE,
    RECONCILIATION_RESOLVE,
    RECONCILIATION_RULE_DRAFT_SAVE,
    RECONCILIATION_RULE_PUBLISH,
    RECONCILIATION_CHANNEL_STATUS_CHANGE
}
